const express = require("express");
const router = express.Router();

const PDFDocument = require("pdfkit");
const multer = require("multer");
const fs = require("fs");
const path = require("path");

const Report = require("../models/Report");

/* ======================================================
   MULTER CONFIG
====================================================== */

const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, "uploads/");
  },

  filename: (req, file, cb) => {
    const uniqueName =
      Date.now() + "-" + file.originalname.replace(/\s/g, "");

    cb(null, uniqueName);
  },
});

const upload = multer({
  storage,

  limits: {
    fileSize: 5 * 1024 * 1024, // 5MB
  },

  fileFilter: (req, file, cb) => {
    const allowedTypes = [
      "image/jpeg",
      "image/jpg",
      "image/png",
      "image/webp",
      "image/heic",
    ];

    if (allowedTypes.includes(file.mimetype)) {
      cb(null, true);
    } else {
      cb(new Error("Only image files are allowed"));
    }
  },
});

/* ======================================================
   PDF GENERATOR
====================================================== */

const generatePDF = (
  doc,
  data,
  beforeImagePath,
  afterImagePath
) => {
  /* ===== HEADER ===== */

  doc
    .fontSize(20)
    .fillColor("#0f172a")
    .text("WORK REPORT", {
      align: "center",
    });

  doc.moveDown(1.5);

  /* ===== REPORT TABLE ===== */

  const startX = 50;
  let y = doc.y;

  const rowHeight = 28;
  const col1Width = 180;
  const col2Width = 310;

  const drawRow = (label, value) => {
    doc
      .lineWidth(1)
      .rect(startX, y, col1Width, rowHeight)
      .stroke("#94a3b8");

    doc
      .rect(startX + col1Width, y, col2Width, rowHeight)
      .stroke("#94a3b8");

    doc
      .fontSize(10)
      .fillColor("#0f172a")
      .text(label, startX + 10, y + 8);

    doc
      .fillColor("#334155")
      .text(
        value ? String(value) : "-",
        startX + col1Width + 10,
        y + 8
      );

    y += rowHeight;
  };

  drawRow("Site Name", data.siteName);
  drawRow("Work Type", data.workType);
  drawRow("Priority", data.priority);
  drawRow("Status", data.status);
  drawRow("Workers", data.workers);
  drawRow("Supervisor", data.supervisor);
  drawRow("Location", data.location);
  drawRow("Photo Number", data.photoNo);
  drawRow("Date & Time", data.dateTime);

  /* ===== DESCRIPTION ===== */

  y += 25;

  doc
    .fontSize(13)
    .fillColor("#0f172a")
    .text("Description", startX, y);

  y += 20;

  doc
    .rect(startX, y, 490, 70)
    .stroke("#94a3b8");

  doc
    .fontSize(10)
    .fillColor("#334155")
    .text(
      data.description || "No Description",
      startX + 10,
      y + 10,
      {
        width: 470,
      }
    );

  /* ===== REMARKS ===== */

  y += 100;

  doc
    .fontSize(13)
    .fillColor("#0f172a")
    .text("Remarks", startX, y);

  y += 20;

  doc
    .rect(startX, y, 490, 70)
    .stroke("#94a3b8");

  doc
    .fontSize(10)
    .fillColor("#334155")
    .text(
      data.remarks || "No Remarks",
      startX + 10,
      y + 10,
      {
        width: 470,
      }
    );

  /* ===== IMAGES ===== */

  y += 110;

  const imageWidth = 220;
  const imageHeight = 150;

  /* BEFORE IMAGE */

  if (
    beforeImagePath &&
    fs.existsSync(beforeImagePath)
  ) {
    doc
      .fontSize(12)
      .fillColor("#0f172a")
      .text("Before Work", startX, y);

    doc.image(
      beforeImagePath,
      startX,
      y + 20,
      {
        fit: [imageWidth, imageHeight],
        align: "center",
        valign: "center",
      }
    );
  }

  /* AFTER IMAGE */

  if (
    afterImagePath &&
    fs.existsSync(afterImagePath)
  ) {
    doc
      .fontSize(12)
      .fillColor("#0f172a")
      .text(
        "After Work",
        startX + imageWidth + 40,
        y
      );

    doc.image(
      afterImagePath,
      startX + imageWidth + 40,
      y + 20,
      {
        fit: [imageWidth, imageHeight],
        align: "center",
        valign: "center",
      }
    );
  }

  /* ===== FOOTER ===== */

  doc
    .fontSize(9)
    .fillColor("#64748b")
    .text(
      "Generated by Real-Time Reporting System",
      50,
      760,
      {
        align: "center",
      }
    );

  doc.end();
};

/* ======================================================
   CREATE REPORT
====================================================== */

router.post(
  "/",
  upload.fields([
    { name: "beforeImage", maxCount: 1 },
    { name: "afterImage", maxCount: 1 },
  ]),

  async (req, res) => {
    try {
      const data = req.body;

      /* ===== VALIDATION ===== */

      if (
        !data.siteName ||
        !data.workType ||
        !data.priority ||
        !data.status
      ) {
        return res
          .status(400)
          .send("Required fields missing");
      }

      /* ===== FILE PATHS ===== */

      const beforeImage =
        req.files?.beforeImage?.[0];

      const afterImage =
        req.files?.afterImage?.[0];

      const beforePath = beforeImage
        ? beforeImage.path.replace(/\\/g, "/")
        : null;

      const afterPath = afterImage
        ? afterImage.path.replace(/\\/g, "/")
        : null;

      /* ===== SAVE REPORT ===== */

      const savedReport = await Report.create({
        ...data,
        beforeImage: beforePath,
        afterImage: afterPath,
      });

      /* ===== GENERATE PDF ===== */

      const doc = new PDFDocument({
        margin: 40,
        size: "A4",
      });

      res.setHeader(
        "Content-Type",
        "application/pdf"
      );

      res.setHeader(
        "Content-Disposition",
        "attachment; filename=report.pdf"
      );

      doc.pipe(res);

      generatePDF(
        doc,
        savedReport,
        beforePath,
        afterPath
      );

    } catch (err) {
      console.error(err);

      res
        .status(500)
        .send("Failed to generate report");
    }
  }
);

/* ======================================================
   PREVIEW REPORT
====================================================== */

router.get("/:id", async (req, res) => {
  try {
    const report = await Report.findById(
      req.params.id
    );

    if (!report) {
      return res
        .status(404)
        .send("Report not found");
    }

    const doc = new PDFDocument({
      margin: 40,
      size: "A4",
    });

    res.setHeader(
      "Content-Type",
      "application/pdf"
    );

    res.setHeader(
      "Content-Disposition",
      "inline"
    );

    doc.pipe(res);

    const beforePath = report.beforeImage
      ? path.join(
          __dirname,
          "..",
          report.beforeImage
        )
      : null;

    const afterPath = report.afterImage
      ? path.join(
          __dirname,
          "..",
          report.afterImage
        )
      : null;

    generatePDF(
      doc,
      report,
      beforePath,
      afterPath
    );

  } catch (err) {
    console.error(err);

    res.status(500).send("Preview failed");
  }
});

/* ======================================================
   DOWNLOAD REPORT
====================================================== */

router.get("/:id/download", async (req, res) => {
  try {
    const report = await Report.findById(
      req.params.id
    );

    if (!report) {
      return res
        .status(404)
        .send("Report not found");
    }

    const doc = new PDFDocument({
      margin: 40,
      size: "A4",
    });

    res.setHeader(
      "Content-Type",
      "application/pdf"
    );

    res.setHeader(
      "Content-Disposition",
      "attachment; filename=report.pdf"
    );

    doc.pipe(res);

    const beforePath = report.beforeImage
      ? path.join(
          __dirname,
          "..",
          report.beforeImage
        )
      : null;

    const afterPath = report.afterImage
      ? path.join(
          __dirname,
          "..",
          report.afterImage
        )
      : null;

    generatePDF(
      doc,
      report,
      beforePath,
      afterPath
    );

  } catch (err) {
    console.error(err);

    res.status(500).send("Download failed");
  }
});

/* ======================================================
   GET ALL REPORTS
====================================================== */

router.get("/", async (req, res) => {
  try {
    const reports = await Report.find().sort({
      createdAt: -1,
    });

    res.json(reports);

  } catch (err) {
    console.error(err);

    res.status(500).send("Fetch failed");
  }
});

/* ======================================================
   DELETE REPORT
====================================================== */

router.delete("/:id", async (req, res) => {
  try {
    const report = await Report.findById(
      req.params.id
    );

    if (!report) {
      return res
        .status(404)
        .send("Report not found");
    }

    /* ===== DELETE BEFORE IMAGE ===== */

    if (report.beforeImage) {
      const beforePath = path.join(
        __dirname,
        "..",
        report.beforeImage
      );

      if (fs.existsSync(beforePath)) {
        fs.unlinkSync(beforePath);
      }
    }

    /* ===== DELETE AFTER IMAGE ===== */

    if (report.afterImage) {
      const afterPath = path.join(
        __dirname,
        "..",
        report.afterImage
      );

      if (fs.existsSync(afterPath)) {
        fs.unlinkSync(afterPath);
      }
    }

    await Report.findByIdAndDelete(
      req.params.id
    );

    res.json({
      message: "Report deleted successfully",
    });

  } catch (err) {
    console.error(err);

    res.status(500).send("Delete failed");
  }
});

module.exports = router;
