const express = require("express");
const router = express.Router();
const PDFDocument = require("pdfkit");
const multer = require("multer");
const fs = require("fs");
const path = require("path");

const Report = require("../models/Report");

/* ================= MULTER ================= */

const upload = multer({
  dest: "uploads/",
});

/* ================= PDF GENERATOR ================= */

const generatePDF = (doc, data, beforePath, afterPath) => {
  /* ===== HEADER ===== */

  doc
    .fontSize(20)
    .fillColor("#1e293b")
    .text("EMERGENCY WORK REPORT", {
      align: "center",
    });

  doc.moveDown(1.5);

  const startX = 50;
  let y = doc.y;

  const rowHeight = 25;
  const col1Width = 170;
  const col2Width = 320;

  /* ===== DRAW TABLE ROW ===== */

  const drawRow = (label, value) => {
    doc
      .lineWidth(1)
      .rect(startX, y, col1Width, rowHeight)
      .stroke("#64748b");

    doc
      .rect(startX + col1Width, y, col2Width, rowHeight)
      .stroke("#64748b");

    doc
      .fillColor("#0f172a")
      .fontSize(10)
      .text(label, startX + 8, y + 7);

    doc
      .fillColor("#334155")
      .text(value || "-", startX + col1Width + 8, y + 7);

    y += rowHeight;
  };

  /* ===== TABLE DATA ===== */

  drawRow("Site Name", data.siteName);
  drawRow("Work Type", data.workType);
  drawRow("Priority", data.priority);
  drawRow("Status", data.status);
  drawRow("Workers", data.workers);
  drawRow("Supervisor", data.supervisor);
  drawRow("Location", data.location);
  drawRow("Photo No", data.photoNo);
  drawRow("Date & Time", data.dateTime);

  /* ===== DESCRIPTION ===== */

  y += 20;

  doc
    .fillColor("#1e293b")
    .fontSize(13)
    .text("Description", startX, y);

  y += 20;

  doc
    .rect(startX, y, 490, 70)
    .stroke("#94a3b8");

  doc
    .fillColor("#334155")
    .fontSize(10)
    .text(
      data.description || "No Description",
      startX + 10,
      y + 10,
      {
        width: 470,
      }
    );

  /* ===== REMARKS ===== */

  y += 100;

  doc
    .fillColor("#1e293b")
    .fontSize(13)
    .text("Remarks", startX, y);

  y += 20;

  doc
    .rect(startX, y, 490, 70)
    .stroke("#94a3b8");

  doc
    .fillColor("#334155")
    .fontSize(10)
    .text(
      data.remarks || "No Remarks",
      startX + 10,
      y + 10,
      {
        width: 470,
      }
    );

  /* ===== IMAGES ===== */

  y += 110;

  const imgWidth = 220;
  const imgHeight = 150;

  /* BEFORE IMAGE */

  if (beforePath && fs.existsSync(beforePath)) {
    doc
      .fillColor("#1e293b")
      .fontSize(12)
      .text("Before Work", startX, y);

    doc.image(beforePath, startX, y + 20, {
      fit: [imgWidth, imgHeight],
      align: "center",
      valign: "center",
    });
  }

  /* AFTER IMAGE */

  if (afterPath && fs.existsSync(afterPath)) {
    doc
      .fillColor("#1e293b")
      .fontSize(12)
      .text("After Work", startX + imgWidth + 40, y);

    doc.image(afterPath, startX + imgWidth + 40, y + 20, {
      fit: [imgWidth, imgHeight],
      align: "center",
      valign: "center",
    });
  }

  /* ===== FOOTER ===== */

  doc.moveDown(12);

  doc
    .fontSize(9)
    .fillColor("#64748b")
    .text(
      "Generated by Real-Time Reporting System",
      50,
      760,
      {
        align: "center",
      }
    );

  doc.end();
};

/* ================= CREATE REPORT ================= */

router.post(
  "/",
  upload.fields([
    { name: "beforeImage" },
    { name: "afterImage" },
  ]),
  async (req, res) => {
    try {
      const data = req.body;

      /* ===== FILE PATHS ===== */

      const beforePath = req.files?.beforeImage?.[0]?.path
        ? req.files.beforeImage[0].path.replace(/\\/g, "/")
        : null;

      const afterPath = req.files?.afterImage?.[0]?.path
        ? req.files.afterImage[0].path.replace(/\\/g, "/")
        : null;

      /* ===== SAVE REPORT ===== */

      const savedReport = await Report.create({
        ...data,
        beforeImage: beforePath,
        afterImage: afterPath,
      });

      /* ===== GENERATE PDF ===== */

      const doc = new PDFDocument({
        margin: 40,
        size: "A4",
      });

      res.setHeader("Content-Type", "application/pdf");

      res.setHeader(
        "Content-Disposition",
        "attachment; filename=report.pdf"
      );

      doc.pipe(res);

      generatePDF(
        doc,
        savedReport,
        beforePath,
        afterPath
      );

    } catch (err) {
      console.error(err);
      res.status(500).send("PDF generation failed");
    }
  }
);

/* ================= PREVIEW REPORT ================= */

router.get("/:id", async (req, res) => {
  try {
    const report = await Report.findById(req.params.id);

    if (!report) {
      return res.status(404).send("Report not found");
    }

    const doc = new PDFDocument({
      margin: 40,
      size: "A4",
    });

    res.setHeader("Content-Type", "application/pdf");

    res.setHeader(
      "Content-Disposition",
      "inline"
    );

    doc.pipe(res);

    const beforePath = report.beforeImage
      ? path.join(__dirname, "..", report.beforeImage)
      : null;

    const afterPath = report.afterImage
      ? path.join(__dirname, "..", report.afterImage)
      : null;

    generatePDF(
      doc,
      report,
      beforePath,
      afterPath
    );

  } catch (err) {
    console.error(err);
    res.status(500).send("Preview failed");
  }
});

/* ================= DOWNLOAD REPORT ================= */

router.get("/:id/download", async (req, res) => {
  try {
    const report = await Report.findById(req.params.id);

    if (!report) {
      return res.status(404).send("Report not found");
    }

    const doc = new PDFDocument({
      margin: 40,
      size: "A4",
    });

    res.setHeader("Content-Type", "application/pdf");

    res.setHeader(
      "Content-Disposition",
      "attachment; filename=report.pdf"
    );

    doc.pipe(res);

    const beforePath = report.beforeImage
      ? path.join(__dirname, "..", report.beforeImage)
      : null;

    const afterPath = report.afterImage
      ? path.join(__dirname, "..", report.afterImage)
      : null;

    generatePDF(
      doc,
      report,
      beforePath,
      afterPath
    );

  } catch (err) {
    console.error(err);
    res.status(500).send("Download failed");
  }
});

/* ================= GET ALL REPORTS ================= */

router.get("/", async (req, res) => {
  try {
    const reports = await Report.find().sort({
      createdAt: -1,
    });

    res.json(reports);

  } catch (err) {
    console.error(err);
    res.status(500).send("Fetch failed");
  }
});

/* ================= DELETE REPORT ================= */

router.delete("/:id", async (req, res) => {
  try {
    const report = await Report.findById(req.params.id);

    if (!report) {
      return res.status(404).send("Report not found");
    }

    /* DELETE FILES */

    if (
      report.beforeImage &&
      fs.existsSync(
        path.join(__dirname, "..", report.beforeImage)
      )
    ) {
      fs.unlinkSync(
        path.join(__dirname, "..", report.beforeImage)
      );
    }

    if (
      report.afterImage &&
      fs.existsSync(
        path.join(__dirname, "..", report.afterImage)
      )
    ) {
      fs.unlinkSync(
        path.join(__dirname, "..", report.afterImage)
      );
    }

    await Report.findByIdAndDelete(req.params.id);

    res.json({
      message: "Report deleted successfully",
    });

  } catch (err) {
    console.error(err);
    res.status(500).send("Delete failed");
  }
});

module.exports = router;
