const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

const generatePDF = (report, res) => {
  const doc = new PDFDocument({
    margin: 40,
    size: "A4",
  });

  /* ================= RESPONSE ================= */

  res.setHeader("Content-Type", "application/pdf");

  doc.pipe(res);

  /* ================= HEADER ================= */

  doc
    .fontSize(22)
    .fillColor("#0f172a")
    .text("WORK REPORT", {
      align: "center",
    });

  doc.moveDown(1.5);

  /* ================= TABLE ================= */

  const startX = 50;
  let y = doc.y;

  const rowHeight = 25;
  const col1Width = 170;
  const col2Width = 320;

  const drawRow = (label, value) => {
    doc
      .lineWidth(1)
      .rect(startX, y, col1Width, rowHeight)
      .stroke("#94a3b8");

    doc
      .rect(startX + col1Width, y, col2Width, rowHeight)
      .stroke("#94a3b8");

    doc
      .fillColor("#0f172a")
      .fontSize(10)
      .text(label, startX + 8, y + 7);

    doc
      .fillColor("#334155")
      .text(value || "-", startX + col1Width + 8, y + 7);

    y += rowHeight;
  };

  drawRow("Site Name", report.siteName);
  drawRow("Work Type", report.workType);
  drawRow("Priority", report.priority);
  drawRow("Status", report.status);
  drawRow("Workers", report.workers);
  drawRow("Supervisor", report.supervisor);
  drawRow("Location", report.location);
  drawRow("Photo No", report.photoNo);
  drawRow("Date & Time", report.dateTime);

  /* ================= DESCRIPTION ================= */

  y += 20;

  doc
    .fillColor("#1e293b")
    .fontSize(13)
    .text("Description", startX, y);

  y += 20;

  doc
    .rect(startX, y, 490, 70)
    .stroke("#cbd5e1");

  doc
    .fillColor("#334155")
    .fontSize(10)
    .text(
      report.description || "No Description",
      startX + 10,
      y + 10,
      {
        width: 470,
      }
    );

  /* ================= REMARKS ================= */

  y += 100;

  doc
    .fillColor("#1e293b")
    .fontSize(13)
    .text("Remarks", startX, y);

  y += 20;

  doc
    .rect(startX, y, 490, 70)
    .stroke("#cbd5e1");

  doc
    .fillColor("#334155")
    .fontSize(10)
    .text(
      report.remarks || "No Remarks",
      startX + 10,
      y + 10,
      {
        width: 470,
      }
    );

  /* ================= IMAGES ================= */

  y += 110;

  const imgWidth = 220;
  const imgHeight = 150;

  /* BEFORE IMAGE */

  const beforePath = report.beforeImage
    ? path.join(__dirname, "..", report.beforeImage)
    : null;

  if (beforePath && fs.existsSync(beforePath)) {
    doc
      .fillColor("#0f172a")
      .fontSize(12)
      .text("Before Work", startX, y);

    doc.image(beforePath, startX, y + 20, {
      fit: [imgWidth, imgHeight],
      align: "center",
      valign: "center",
    });
  }

  /* AFTER IMAGE */

  const afterPath = report.afterImage
    ? path.join(__dirname, "..", report.afterImage)
    : null;

  if (afterPath && fs.existsSync(afterPath)) {
    doc
      .fillColor("#0f172a")
      .fontSize(12)
      .text("After Work", startX + imgWidth + 40, y);

    doc.image(afterPath, startX + imgWidth + 40, y + 20, {
      fit: [imgWidth, imgHeight],
      align: "center",
      valign: "center",
    });
  }

  /* ================= FOOTER ================= */

  doc
    .fontSize(9)
    .fillColor("#64748b")
    .text(
      "Generated by Real-Time Reporting System",
      50,
      760,
      {
        align: "Bottom",
      }
    );

  /* ================= END ================= */

  doc.end();
};

module.exports = generatePDF;
